-- ПРОСТОЕ ОТКЛЮЧЕНИЕ RLS ДЛЯ ВСЕХ ТАБЛИЦ
-- Этот скрипт ТОЛЬКО отключает RLS, не создает никаких политик

-- Отключаем RLS для всех таблиц
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS students DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lessons DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS recurring_schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_active_role DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tutor_earnings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tutor_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS manager_commissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS manager_sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS salary_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS action_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS transaction_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lesson_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lesson_deductions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lesson_refill_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lesson_refill_reminders DISABLE ROW LEVEL SECURITY;
